- .github/workflows/build-and-deploy.yml
Seems that the `${{ ... }}` construct is not recursive: embedding it within itself won't have the inner one expanded. In other words, [triggering an `i686` build of the `mintty` package resulted in this very ugly title](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3730919260):
Build and deploy mintty (${{ inputs.architecture }})
Let's avoid that by using [the `format()` function](https://docs.github.com/en/actions/learn-github-actions/expressions#format).
> build-and-deploy: fix the run-name for MSYS builds

- .github/workflows/build-and-deploy.yml
I just tried to deploy the i686 version of the MSYS variant of `curl`, but ran into [problems](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3747937026/jobs/6364819440).
This PR hopefully fixes those problems.
> build-and-deploy(i686): address the dreaded `.dll` base address problem

- .github/workflows/build-and-deploy.yml
Note that this only works for self-hosted runners. GitHub Actions will pick up and use the first available arm64 runner.
Here's a successful run for `mingw-w64-openssl` on `aarch64`: https://github.com/dennisameling/git-for-windows-automation/actions/runs/3735260060/jobs/6338362688. Note that I had to do some manual fixes as the pipeline assumes it has a GitHub app (`GH_APP_ID` and `GH_APP_PRIVATE_KEY`) at its disposal. In my run, I simply replaced that with a PAT by doing `const accessToken = ${{ secrets.DENNIS_PAT }}`
> build-and-deploy: add support for arm64 builds

- .github/workflows/create-azure-self-hosted-runners.yml
- azure-self-hosted-runners/azure-arm-template-example-parameters.json
- azure-self-hosted-runners/azure-arm-template.json
- azure-self-hosted-runners/post-deployment-script.ps1
This is a CI pipeline to create one or multiple Azure arm64 VMs with GfW and the GitHub Actions runner preinstalled and provisioned. The VMs are deallocated immediately after creation so they are prepared for later use.
Here's an example run: https://github.com/dennisameling/azure-arm64-gh-actions-runner/actions/runs/3740740959/jobs/6349467898
The runner is then added to the repo correctly 🎉 it's offline because we deallocate the VM immediately after setup in the CI pipeline.
After running a job on the runner, it's automatically removed thanks to the `--ephemeral` flag:
> Add CI pipeline for creating self-hosted runners

- .github/workflows/open-pr.yml
When opening a Pull Request, we would like to automatically close the corresponding `component-update` ticket, if there is any.
Unfortunately, it is not _quite_ trivial to search for such tickets. One frustrating aspect is that some updates have the version number prefixed with `v` while others do not. And the search on GitHub is a bit strict about that: if you search for `0.10.1`, you won't find a ticket mentioning `v0.10.1` and the opposite is also true.
We already started to special-case at least Git LFS, but it's a bit of a whack-a-mole to do that for all components we track in Git for Windows.
Let's instead search for the version in both forms: both prefixed with `v` as well as without.
This addresses
https://github.com/git-for-windows/gfw-helper-github-app/issues/18
> open-pr: try harder to find a corresponding `component-update` ticket

- azure-self-hosted-runners/post-deployment-script.ps1
As reported [here](https://github.com/git-for-windows/git-for-windows-automation/pull/4#issuecomment-1363442879), the `Get GPG key(s)` step wasn't working on arm64.
```
gpg: key 88138B9E1A9F3986: public key "Johannes Schindelin <johannes.schindelin@gmx.de>" imported
gpg: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg: waiting for the agent to come up ... (5s)
gpg: waiting for the agent to come up ... (4s)
gpg: waiting for the agent to come up ... (3s)
gpg: waiting for the agent to come up ... (2s)
gpg: can't connect to the agent: IPC connect call failed
```
After way too many (failed) attempts to fix things, I debugged by trying `gpg-agent --daemon` directly in the pipeline and found the following:
```
gpg-agent[768]: directory …
```
> `build-and-deploy`: arm64 fixes for GPG signing

- .github/workflows/build-and-deploy.yml
The underlying problem why earlier attempts to deploy `mingw-w64-aarch64-git-extra` failed (e.g. [this one](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3760961637)) has _nothing_ to do with ARM64 at all. The problem is that GNU Privacy Guard wants to put a socket into `~/.gnupg/` whose complete path (including NUL byte) has to fit within a mere 108 bytes.
With this proposed work-around, [the build succeeded](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3825211124/jobs/6508034961) (I specifically only ran the _build_, not the _deploy_ part just yet, so that we can verify that the build _actually_ worked).
> Fix `build-and-deploy` on self-hosted ARM64 agents

- .github/workflows/build-and-deploy.yml
As discussed [here](https://github.com/git-for-windows/git-sdk-arm64/issues/3#issuecomment-1371496963).
> Prepare for building arm64 versions of the `wintoast` and `git-credential-manager` packages

- .github/workflows/build-and-deploy.yml
For MSys packages we start two parrallel runs of this workflows, that can succeed or fail independently from one another. We need to use two separate check runs to accurately represent their status. The corresponding change in gfw-helper-github-app is part of https://github.com/git-for-windows/gfw-helper-github-app/pull/17
> build-and-deploy: use separate check runs for each MSys architecture

- .github/workflows/open-pr.yml
- update-scripts/checksums/mingw-w64-git-lfs
- update-scripts/version/bash
Some packages set `pkgver` in a way that doesn't quite work with our generic `sed` invocation. Teach our `open-pr` workflow to use a package specific update script for that step like we already do with the `updpkgsums` step.
This fixes #1
> Teach open-pr.yml about special pkgver constructs

- .github/workflows/create-azure-self-hosted-runners.yml
- .github/workflows/delete-self-hosted-runner.yml
- azure-self-hosted-runners/azure-arm-template-example-parameters.json
- azure-self-hosted-runners/azure-arm-template.json
- azure-self-hosted-runners/post-deployment-script.ps1
For now, we manually spin up the runners. It makes more sense to keep them running so that they can pick up the job immediately instead of deallocating them and then manually restart them.
> Optionally keep self-hosted-runners allocated after creating them

- .github/workflows/build-and-deploy.yml
This is similar in spirit to #12, just for Git LFS (which I really should have included but I forgot that it was in the same boat as wintoast/Git Credential Manager).
> build-and-deploy: use hosted runners for git-lfs for ARM64

- azure-self-hosted-runners/azure-arm-template.json
We were using the older win11-21h2 SKU. Let's use the newer SKU instead.
> azure-arm-template: bump image SKU to win11-22h2

- .github/workflows/create-azure-self-hosted-runners.yml
- azure-self-hosted-runners/azure-arm-template.json
Used [this](https://github.com/azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.compute/vm-custom-script-output) for inspiration.
> azure-arm-template: get CustomScriptExtension output

- azure-self-hosted-runners/post-deployment-script.ps1
**GitHub git-windows and Action runner**
- Added check as was asked for both ActionRunner and GitHub git-windows
- Now all data for GitHub git-windows and ActionRunner are stored in the objects $GitHubAction and $GitHubGit
- Used invoke-restmethod to eliminate overhead and it makes it easier to go over to PSCore later on. Also I added the accept and API version in the header. With this you don't need to convert it from json etc. it's easier.
**Ensure that Action runner service was created**
Added so it will look if it has been created 3 times 3 seconds apart before it write error as sometime it can take time for the service to be created.
**Stop Service, actions.runner.***
- As you was using * I'm guessing that it can be many services so I did add an foreach loop on them.
- Inside the …
> self-hosted runner: always use latest Git for Windows and GitHub Actions version (plus some PowerShell cleanups)

- .github/workflows/open-pr.yml
when creating e60ad7c (open-pr: support update scripts to set `pkgver`, 2022-12-14) I copy-edited the wrong part of the path which lead to nonsense.
> open-pr: actually use version update scripts

- .github/workflows/open-pr.yml
- update-scripts/version/openssh
The `curl` executable in `C:\Windows\system32` exclusively uses Secure Channel as TLS backend. This is usually fine, except when one needs to talk to a TLS v1.3-only host and one is stuck with Windows prior to Windows 11 (where Secure Channel simply does not support TLS v1.3).
This happens to be exactly the case that caused the workflow run to fail that wanted to open a PR for OpenSSH v9.2p1.
Let's just use our own MINGW `curl.exe` instead.
> open-pr: avoid using system curl (because it can't do TLS v1.3)

- .github/workflows/build-and-deploy.yml
Successful run that includes these changes: https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4114193682
> build-and-deploy: several optimizations, mostly to facilitate arm64 workflows

- .github/workflows/create-azure-self-hosted-runners.yml
When multiple parallel deployments were requested, all deployments after the first [failed](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4116757131/attempts/1) with `Unable to edit or replace deployment 'azure-arm-template'`. Let's use unique deployment names related to the generated VM name so that we not only can support parallel deployments, but also should be able to have a better Azure deployment log history.
Ref: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-powershell#deployment-name
> create-azure-self-hosted-runners: use unique deployment names

- .github/workflows/create-azure-self-hosted-runners.yml
In a recent Actions run, we ran into the CPU quotum that was set in Azure (max. 20 cores across all active VMs). By lowering the vCPU count on the VMs from 8 to 4, we can increase the number of simultaneous VMs from 2 to 5.
Next to that, the current performance is mostly limited by x64-emulation of unixy-tools like Bash anyway. The workflows really aren't using all the CPU cores, only during things like Clang-compilation.
Ref: https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4144779320/jobs/7168260908
> self-hosted-runners: use 4-core VMs

- .github/workflows/git-artifacts.yml
- .github/workflows/tag-git.yml
- create-artifacts-matrix.js
- get-bundle-artifacts-artifact.js
Successful run: https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3985052314
> Port `git-artifacts` pipeline to `git-for-windows-automation`

- .github/workflows/open-pr.yml
We've split a step into two, but left the `&&` at the end of the first. That leads to failures like this one:
https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4150668809/jobs/7180481501
> open-pr: don't concatenate  after last command of a step

- .github/workflows/build-and-deploy.yml
- .github/workflows/create-azure-self-hosted-runners.yml
- get-installation-access-token.js
GitHub Apps' installation access tokens expire after an hour.
That is the reason why the [`mingw-w64-gnutls`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4153007326/jobs/7184357891) and the [`mingw-w64-gnutls(aarch64)`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4153007483/jobs/7184358147) builds failed: it took more than an hour to build those Pacman packages.
Work around such issues by refreshing the installation access token if needed.
[Here](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4161550580/jobs/7199654542#step:6:50) is a workflow run demonstrating (via essentially a dry-run) that the non-expiring case [still works as expected](https://github.com/git-for-windows/git-for-windows-automation …
> Deal with expired installation access tokens

- .github/workflows/git-artifacts.yml
So far, we have an implementation of the common flow where the `tag-git` workflow is started to create "bundle-artifacts" including a Git bundle with the newly-tagged Git version and another Git bundle with the updated release notes.
However, for the just-published Git for Windows v2.39.2, we would like to build the ARM64 flavor of the artifacts, i.e. for an _existing_ tag.
Let's introduce two new inputs (referring to an existing tag and an existing build-extra revision) that can be used instead of the input referring to a `tag-git` workflow run, and handle that scenario, too.
> git-artifacts: allow building from an existing tag

- .github/workflows/open-pr.yml
This works around the problems identified in https://github.com/git-for-windows/git/issues/4303#issuecomment-1436590886.
Proof that caching works: https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4230831858/jobs/7348623407#step:8:17
Proof that pushing works (or more correctly: generating the authorization header): https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4230831858/jobs/7348623407#step:14:21
> open-pr: avoid caching error 127

- .github/workflows/build-and-deploy.yml
During my work on the `release-git` workflow, I introduced a bug that caused the deployments in https://github.com/git-for-windows/MSYS2-packages/pull/92#issuecomment-1471552897 to fail.
This PR fixes that.
> Fix the Check Run mirroring in `build-and-deploy`

- .github/workflows/build-and-deploy.yml
- .github/workflows/open-pr.yml
- update-scripts/ensure-not-yet-deployed.sh
This PR adds a sanity check that aborts early if we're about to deploy a package version that has _already_ been deployed.
This fixes https://github.com/git-for-windows/git-for-windows-automation/issues/15
> open-pr/build-and-deploy: avoid re-deploying existing package versions

- repository-updates.js
While the `release-git` workflow run looked as if it performed all the repository updates as expected, it actually only fetched from the `MINGW-packages.bundle` but did not merge the change. As a consequence, the `git push` had no updates to offer.
I fixed that by manually downloading the bundle in [the `git-artifacts (x86_64)` run](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4413112845#artifacts)'s `pkg-x86_64` artifact and pushing https://github.com/git-for-windows/MINGW-packages/commit/13a189253e9fef04e18fdbd51254930905c3b9b1.
However, it is a better idea to fix this in the `release-git` workflow than to do that manual fix-up for every release.
> Fix pushing `MINGW-packages` updates in the `release-git` workflow

- .github/workflows/release-git.yml
- repository-updates.js
We already have a check to verify that the `release` branch is up to date with the `main` branch before even starting the `release-git` workflow run for real.
But we can do better than telling the user when the branch is not up to date: We can easily try to update it in the workflow run ;-)
> release-git: update the `release` branch if necessary

- .github/actions/repository-updates/action.yml
- .github/workflows/git-artifacts.yml
- repository-updates.js
The `build-extra` repository has a `versions/` subdirectory in which all of the Git for Windows versions' package versions are tracked. This is supposed to happen automatically in the release automation.
However, when I ported the release automation from the Azure Release Pipeline to a GitHub workflow, I simply missed that part, so it was not done for v2.40.0 (I fixed that manually in the meantime). Here is a PR to fix that for the next time.
Note: this PR conflicts with https://github.com/git-for-windows/git-for-windows-automation/pull/42 and will need to be rebased after that PR is merged.
> Do commit `package-versions.txt` files in the `release-git` workflow

- .github/actions/check-run-action/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/tag-git.yml
- check-runs.js
The [latest `git-artifacts` run failed](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/5001089177) because the installation token was created more than 10 minutes before the `portable` and the `nuget` jobs were actually started (they were queued for a long time because of some concurrent workflow runs using up the contingent of hosted runners available to the Git for Windows project).
This uncovered the fact that we fail to re-generate new installation tokens because the Action lacks the proper information: it needs a repository to work with, but that information was not passed as parameter.
This is a wide-spread issue: the `check-run-action` actually requires the owner/repo information in case a new installation token needs to be generated.
This PR fixes all …
> Fixes for check run updates

- .github/workflows/release-git.yml
We already have code to fast-forward a `release` branch that is not up to date.
By mistake, I _deleted_ the `release` branch, however: the repository settings are such that merging a PR deletes its "head" branch, and I had merged the `release` branch into the `main` branch. Deleting the branch [broke the logic to fast-forward `release`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/5028408563/jobs/9019086520#step:3:50).
Let's handle missing `release` branches the same as out-of-date branches, and try to push the current `main` to the `release` branch.
> release-git: handle missing `release` branch gracefully

- .github/actions/github-release/action.yml
According to the [REST API documentation of `create-a-release`](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release), the `make_latest` should default to `true`.
However, when releasing Git for Windows v2.42.0 this was not so. I had to mark it as "latest" manually, and I only realized this because the `gitforwindows.org` update would fail (because it would still pick up v2.41.0(3) as the latest release).
Let's just make it explicit that we want to mark it as the latest version (at least as long as we're not publishing a pre-release).
> /release: explicitly mark full versions as the latest GitHub Release

- update-scripts/version/mingw-w64-clang
We want to build our own smaller Clang for ARM64, teach open-pr how to update it. This update script uses the update-clang-from-msys2.sh script from https://github.com/git-for-windows/MINGW-packages/pull/75
> open-pr: support Clang

- .github/workflows/git-artifacts.yml
As @rimrul noticed, between v2.43.0-rc1 and v2.43.0-rc2 we [did not reset `pkgrel=1`](https://github.com/git-for-windows/git/pull/4692#issuecomment-1817775282).
This is part 2 (The Conclusion) of the two-parter to address this (and I plan on merging this today, [in time for v2.43.0 final](https://gh.io/gitCal)) and requires https://github.com/git-for-windows/build-extra/pull/534 to be merged first (hence it is opened as draft PR to avoid merging it accidentally before that other PR).
> `/git-artifacts`: reset `pkgrel=1` between releases

- .github/actions/init-g4w-sdk-for-pacman/action.yml
- .github/workflows/open-pr.yml
- .github/workflows/updpksums.yml
Every once in a while, the Git for Windows project receives Pull Requests from new contributors, which is great!
It can be quite frustrating, then, if something goes awry due to the unintuitive and at times arcane paradigms, e.g. Pacman's checksums that are ignored during an `sdk build` (because running `updpkgsums` is slow and gets in the way of developing exciting features).
As suggested in https://github.com/git-for-windows/gfw-helper-github-app/issues/28, we should have automation for this. Here is the `git-for-windows-automation` part, and [I already used a development version of this GitHub workflow](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/7237776837/job/19717837426) (triggered on `push` because `workflow_dispatch` can only be triggered if the …
> Add a GitHub workflow to run `updpkgsums` in PRs

- .github/workflows/build-and-deploy.yml
Needs https://github.com/git-for-windows/build-extra/pull/539 to be merged first.
The intricacies of updating the Git for Windows SDKs are not _quite_ trivial. For one, you have to make sure to call `pacman` another time if "system packages" such as `msys2-runtime` have been updated. Also, in the end `mingw-w64-git-extra` has to be installed so that that package's post-install script can adjust a couple of system files in accordance with Git for Windows' requirements.
These intricacies are documented and automated in the `update-via-pacman.ps1` script that is run as part of the `sync` GitHub workflows that are installed in the `git-sdk-*` repositories.
It only makes sense to use the same automation when building Git for Windows' packages, so let's do this.
This fixes …
> build-and-deploy: use `update-via-pacman.ps1` instead of a home-grown `pacman -Syyu`

- .github/workflows/build-and-deploy.yml
In the `build-and-deploy` GitHub workflow, we try to clean up the GPG files before finishing the job, but it seems that as of GPG v2.4.x, [this fails](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/7906810424/job/21582488405#step:20:20). In other words, it looks as if we need to stop the GPG agent before doing that. 
So let's do that, and while at it, also make sure that the `dirmngr` (GPG's daemon that takes care of talking to keyservers) is stopped, too.
> build-and-deploy: stop GPG agent before trying to remove GPG files

- .github/workflows/build-and-deploy.yml
This was a mistake that slipped through via https://github.com/git-for-windows/git-for-windows-automation/pull/71.
This just broke the builds of `mintty` (_after_ successfully deploying the packages): [i686](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/8039156102/job/21955864065#step:20:22) and [x86_64](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/8039155942/job/21955863606#step:20:22).
The symptom is the error message "Component not found" in the "Clean up temporary files" step.
> build-and-deploy: spell `dirmngr` correctly

- .github/workflows/create-azure-self-hosted-runners.yml
- azure-self-hosted-runners/azure-arm-template.json
Updates the self hosted runner image and also makes it configurable through env vars.
Note: the rest of this PR description was for an older version of this PR and therefore collapsed.
<details>
<summary>See prior PR description</summary>
As discussed [here](https://github.com/git-for-windows/git-for-windows-automation/issues/59#issuecomment-1821185442), let's add some cleanup logic for Azure VMs that we no longer need.
> Another idea: we should be able to teach GitForWindowsHelper to detect failed create-self-hosted-runner runs and automatically kick off the delete run, no?
In this PR, I added logic that goes through the resource group and deletes leftover VMs. That way, it's not strictly linked to failed runs. I think this is a more robust way to ensure leftover VMs are deleted, but …
> Self hosted runner: update image and make configurable through env vars

- azure-self-hosted-runners/post-deployment-script.ps1
This is not installed by default, but some of GfW's scripts expect it to be installed. Let's get it installed through the post-deployment script.
Can confirm it works as expected:
```
Starting post-deployment script.
Enabling Windows Developer Mode...
Enabled Windows developer mode.
Adding Microsoft Defender Exclusions...
Finished adding Microsoft Defender Exclusions.
Downloading Git for Windows...
Installing Git for Windows...
Finished installing Git for Windows.
Downloading pwsh...
Installing pwsh...
Copying pwsh-preview.cmd to pwsh.cmd as a temporary measure until 7.5.0 is out...
Finished installing pwsh.
Downloading GitHub Actions runner...
Installing GitHub Actions runner 2.316.0 as a Windows service with labels self-hosted,Windows,ARM64...
Configuring the runner to shut down …
```
> self-hosted runners: install pwsh

- .github/workflows/build-and-deploy.yml
- .github/workflows/create-azure-self-hosted-runners.yml
- .github/workflows/git-artifacts.yml
Last night, a `mingw-w64-openssl (aarch64)` job [timed out after 6h](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/9374447637/job/25810488159#step:12:28), which cost quite a bit of Azure resources.
The reason was most likely that finicky MSYS2 runtime which hangs on Windows/ARM64 quite often.
Let's add timeouts to workflows' steps to avoid incurring these Azure costs.
> workflows: add timeouts, address linter issues

- .github/workflows/create-azure-self-hosted-runners.yml
The 24h2 version of Windows 11 introduces a new x64 emulation engine: Prism. It promises improved performance, and maybe it'll help resolve some of the mysterious arm64 hangs we've been experiencing...
Ref: https://learn.microsoft.com/en-us/windows/arm/apps-on-arm-x86-emulation#prism
> self-hosted runners: upgrade to 24h2

- github-release.js
It is a nice thing to have for users, and therefore I just created one for the latest Git for Windows version at
https://github.com/git-for-windows/git/discussions/5035.
Let's automate this.
For details about the used REST API endpoint, see
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release--parameters
> release: create a discussion for every Git for Windows release

- .github/workflows/break-pacman-upload-lease.yml
This fixes https://github.com/git-for-windows/git-for-windows-automation/issues/40
> Add a workflow to break a pacman upload lease

- .github/workflows/open-pr.yml
- update-scripts/version/msys2-runtime
This adds the backend for the upcoming support for `/open pr` in git-for-windows/msys2-runtime PRs.
> open-pr: support msys2 runtime

- .github/workflows/open-pr.yml
- update-scripts/checksums/innosetup
- update-scripts/version/innosetup
This is a companion PR to https://github.com/git-for-windows/gfw-helper-github-app/pull/88; Together, they allow updating InnoSetup via `/open pr` from within the tickets that are opened by [the `monitor-components` workflow](https://github.com/git-for-windows/git/actions/workflows/monitor-components.yml).
[Here](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/9907328672) is a successful run that opened https://github.com/git-for-windows/build-extra/pull/568 (the branch had one commit on top to trigger the build on `push`, which has been dropped before opening this here PR).
> open-pr: support updating InnoSetup

- .github/actions/github-release/action.yml
This was the intention of #85, but that PR only changed the call that creates the draft release.
Apparently the intention to create a discussion post is _not_ stored when creating a draft release, though, sadly. Therefore we need to state that intention again when we do publish the release.
This problem was reported [here](https://github.com/git-for-windows/git-for-windows-automation/pull/85#issuecomment-2259878251).
> github-release: do create a discussion post for each new Git for Windows version

- .github/workflows/create-azure-self-hosted-runners.yml
- .github/workflows/delete-self-hosted-runner.yml
Let's use the latest version, as the one we're currently using is from December 2022.
Ref: https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#december-06-2022
Ref: https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#september-03-2024
> self hosted runners: update Azure CLI version to latest

- azure-self-hosted-runners/post-deployment-script.ps1
Starting with version 7.4.3 of PowerShell, Windows arm64 MSIs [are added to the releases](https://github.com/PowerShell/PowerShell/releases/tag/v7.4.3), so we no longer need to hardcode the preview version.
Also, during local testing, I forgot to run PowerShell as administrator and the installation of `pwsh` silently failed. Let's [prevent the script from starting if we're not an admin](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7.4#-runasadministrator). This is mostly a nice to have for local testing, since the post-deployment script on the self-hosted runner always runs as admin.
> self-hosted runners: use latest `pwsh` version now that arm64 MSIs are available

- .github/workflows/cleanup-self-hosted-runners.yml
The `azure/cli` GitHub Action runs in a Docker container with Alpine or Azure Linux, meaning that many tools like `node` and `gh` (which we rely on) aren't available.
Since the Azure CLI is available in the GitHub-hosted `ubuntu-latest` image anyway, let's leverage that instead. In the end, it has all the other tools we need as well.
Ref: https://github.com/actions/runner-images/blob/ce2a3e8e67858dc8c3dd77aca6b29e2956d934ed/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L105
> Self-hosted runner cleanup: use Ubuntu instead of azure/cli action

- .github/workflows/azure-login/action.yml
- .github/workflows/cleanup-self-hosted-runners.yml
- .github/workflows/create-azure-self-hosted-runners.yml
We're [seeing](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/11025772033/job/30621189230) intermittent `OSProvisioningTimedOut` errors on VM creation, which typically happens within 20-40 mins of the deployment hanging. Most creation jobs seem to work fine, though.
Let's try and find out what's going wrong, so we can see if we need to fix things on our end.
> Azure self-hosted runners: show logs on failure

- .github/actions/github-release/action.yml
- .github/workflows/release-git.yml
- github-release.js
Merge together with https://github.com/git-for-windows/gfw-helper-github-app/pull/110
The `git-artifacts` pipeline already supports ARM64, so we can add support for it in the `release-git` workflow as well.
> release-git: add support for arm64

- .github/actions/pacman-packages/action.yml
- .github/workflows/release-git.yml
In earlier commits, we added suppport for ARM64 to the release pipelines, but there's a couple more places to update. Let's do that.
> release-git: add missing aarch64 input to github-release action

- azure-self-hosted-runners/post-deployment-script.ps1
Closes #28 
2.47.1 is the first version of Git for Windows for which native arm64 binaries are being published. Let's use those moving forward, for better performance.
Ref: https://github.com/git-for-windows/git/releases/tag/v2.47.1.windows.1
> self-hosted runners: use native arm64 version of GfW

- azure-self-hosted-runners/post-deployment-script.ps1
Follow-up of https://github.com/git-for-windows/git-for-windows-automation/pull/101
There was a bug in the regex that finds the sha256 hash corresponding to the Git binary. Doing things like `[Regex]::Escape` directly in a string interpolation, apparently isn't supported by PowerShell. It just returned an empty string in the string interpolation.
This has surprisingly worked until now, because `Git-2.47.1-64-bit.exe` was [always the first binary in the list of assets](https://github.com/git-for-windows/git/releases/tag/v2.47.1.windows.1), so the corresponding hash was found. Now that we're getting the native `-arm64.exe` binary, the bug in the logic got exposed.
This commit fixes the bug by assigning the escaped asset name to a dedicated variable first.
> post-deployment-script: fix regex for sha256

- update-scripts/version/mingw-w64-llvm
As we noticed in https://github.com/git-for-windows/MINGW-packages/pull/132 the update script for llvm currently doesn't properly handle added or removed patches. This can break the llvm build. Update the script to handle these patches.
> llvm: add changed patches

- .github/workflows/release-git.yml
For quite a while now, those emails were rejected by the Git mailing list due to some Spamhaus rule. This is quite annoying, but cannot be helped because, well, because reasons.
So let's just print out the announcement email to the log, thusly requiring a manual step after the release is done.
> release-git: require the announcement email to be sent manually

- .github/workflows/git-artifacts.yml
I ran into so many troubles while working on v2.48.0-rc2 that I decided to take a bit of time to look carefully at all the changes that were integrated over the holidays (when most people stayed away from their keyboards, and I should have done the same). While kicking the tires of Git for Windows v2.48.0-rc1 I noticed that the Pacman package recorded a different packager than signer. And after I was half-way through debugging this, I realized that I had already fixed this during the embargoed release last year.
And sure enough, when I looked at the commits that I had meant to merge back into `git-for-windows-automation`, I found the fix: https://github.com/git-for-windows/git-for-windows-automation/commit/ff048920f66406594a053b003d3cc43d585f5f37
Sadly, the commits are in nowhere near the …
> git-artifacts: a couple of minor fixes

- github-release.js
The SHA-256 checksums of the Git for Windows release artifacts are listed at the bottom of Git for Windows' announcement emails.
Certain of those artifacts are deemed more important than others and are hence listed first. For example, x86_64 is nowadays considered much more important than i686 (which is deprecated, after all). To present the artifacts in such an order, the `artifactName2Rank()` function hard-codes CPU architecture rankings.
When ARM64 artifacts were included, this ranking was not adjusted, and as a consequence ARM64 ranked way on the bottom. However, ARM64 is the future (or will be, once GitHub comes through with the promise of hosted runners) because of battery life, performance potentials, etc, and it should therefore outrank i686.
Let's make it so!
> release-git: rank ARM64 higher than 32-bit

- .github/workflows/break-pacman-upload-lease.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/git-artifacts.yml
- .github/workflows/open-pr.yml
- .github/workflows/prepare-embargoed-branches.yml
- .github/workflows/release-git.yml
- .github/workflows/updpkgsums.yml
- .github/workflows/upload-snapshot.yml
- github-release.js
- prepare-embargoed-branches.sh
- repository-updates.js
In 2017, I started working on [the `GitArtifacts` Azure Pipeline](https://dev.azure.com/git-for-windows/git/_build?definitionId=34&_a=summary) to not only produce Git for Windows' artifacts (such as installer, portable Git, MinGit, etc) for _full_ releases, but basically on every push. The resulting artifacts were uploaded to Azure Blobs and for convenience, an index of all of those snapshots was maintained at https://wingit.blob.core.windows.net/files/index.html.
This all depends on Azure Blob storage that is hosted in my personal Azure account.
I recently stumbled over [yet another excellent letter to open-source maintainers](https://xuanwo.io/2024/10-a-letter-to-open-source-maintainers/) that had this great [piece](https://xuanwo.io/2024/10-a-letter-to-open-source-maintainers/#always-re …
> Start migrating Git for Windows' snapshot builds to GitHub Actions

- .github/workflows/open-pr.yml
- update-scripts/version/bash
- update-scripts/version/msys2-runtime
Previously, we used the title `msys2-runtime: update to <commit OID>` which is as correct as it is unhelpful.
Let's use `<pkgver>-<pkgrel>`  instead of `<commit OID>`. Proof that it works: [the `open-pr` run](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/13006636896/job/36274972609) that opened https://github.com/git-for-windows/MSYS2-packages/pull/210.
> open-pr: use more pleasant commit/PR titles when handling the `msys2-runtime` package

- update-scripts/tag-git.sh
For almost eight years, Git for Windows' snapshots were hosted at https://wingit.blob.core.windows.net/files/index.html, i.e. on Azure Blobs.
As of a combination of PRs (https://github.com/git-for-windows/git-for-windows-automation/pull/109, https://github.com/git-for-windows/gfw-helper-github-app/pull/117), snapshots are not only now built and deployed via GitHub Actions instead of Azure Pipelines (and ARM64 artifacts are now included, too), they are also hosted [on GitHub](https://github.com/git-for-windows/git-snapshots/releases/), with the main page being hosted [on GitHub Pages](https://github.com/git-for-windows/git-snapshots/commits/gh-pages).
Therefore, the original link now redirects to a new location (which is also a lot easier to remember): …
> tag-git: use the new Git for Windows snapshots URL

- .github/workflows/upload-snapshot.yml
This was a clear oversight of mine: the `Min` and `Portable` prefix before `Git` are _optional_, otherwise _only_ MinGits and PortableGits get included in the snapshot (which is what happened over the past couple of snapshots, e.g. [here](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/13207883283/job/36875241639#step:5:75), which I will have to fix separately).
> upload-snapshot: include the Git for Windows installers in the snapshots again

- .github/actions/pacman-packages/action.yml
- .github/workflows/build-and-deploy.yml
To disentangle Git for Windows' Pacman repository from my personal Azure account a bit, I started transitioning it to https://github.com/git-for-windows/pacman-repo.
In https://github.com/git-for-windows/build-extra/pull/595, I prepare `pacman-helper.sh` (which is Git for Windows' work horse for Pacman package deployments) to dual-deploy both to the old and to the new Pacman repository. Naturally, this needs the appropriate GitHub token to work. So here is the PR to adjust _the_ two remaining call sites in Git for Windows' automation to provide said token.
> Start transitioning to Git for Windows' new Pacman repository

- .github/workflows/remove-packages-from-pacman-repository.yml
Calls pacman-helper.sh quick_remove.
For https://github.com/git-for-windows/git-sdk-32/issues/39#issuecomment-2664159567
> Add remove-packages-from-repo action.

- .github/workflows/remove-packages-from-pacman-repository.yml
This, combined with https://github.com/git-for-windows/build-extra/pull/598, fixes the `remove-packages-from-pacman-repository` workflow.
> Follow-up fixes for the workflow to remove packages from Git for Windows' Pacman repository

- azure-self-hosted-runners/post-deployment-script.ps1
Previously, the Actions runner was run under the `NT AUTHORITY\NETWORK SERVICE` account, which lacks the permissions to install Git for Windows. However, that is precisely what the `git-artifacts` workflow is supposed to do.
Tweaking the `./config.cmd` invocation by adding `--windowslogonaccount "NT AUTHORITY\SYSTEM"`` fixes the issue.
> self-hosted-runner: run the Actions runner under the SYSTEM account

- create-artifacts-matrix.js
As announced multiple times and also documented in detail at https://gitforwindows.org/32-bit, Git for Windows will no longer publish 32-bit installers, portable Gits and such.
The only i686 artifacts that will be published are the MinGit ones, until April 2029.
This addresses https://github.com/git-for-windows/git/issues/5394.
> git-artifacts: stop building i686 artifacts except MinGit

- .github/workflows/git-artifacts.yml
In #117, I already tried to address this. But I forgot that the default, if left unspecified which artifacts to build, is to build all of them (with "all" being hard-coded also in the `Configure environment` step of the `git-artifacts` workflow).
So let's adjust this step, too.
This closes https://github.com/git-for-windows/git/issues/5394.
> git-artifacts: _really_ stop building i686 artifacts except MinGit

- update-scripts/tag-git.sh
As per https://github.com/git-for-windows/git/discussions/5473, Git for Windows' Google Group is shut down.
> No longer post to the now-retired Google Group

- .github/workflows/break-pacman-upload-lease.yml
It probably won't matter for much longer, but I finally figured out why on Earth the workflow run was skipped consistently: It was the clean-up step (which apparently looked nefarious to some automated gatekeeper tasked to keep miners out of Actions).
> Fix breaking the Pacman lease

- .github/workflows/release-git.yml
Since the Git mailing list so helpfully denies us the ability to post emails from Azure IPs, Git for Windows' announcement emails have to be sent manually again (see #105), which is a hassle.
To make the process easier, add a PR comment with a direct link to the artifact containing the announcement email, and while at it also prepare an announcement to share on Bluesky.
> release-git(announcement): add a helpful comment

- .github/actions/github-release/action.yml
- .github/workflows/release-git.yml
Along with a few minor fixes, this delays adding the PR comment until the time when it makes sense.
> `release-git`: only add the helpful PR comment after the GitHub Release has been published

- .vscode/launch.json
- .vscode/settings.json
Seeing as we have quite a lot of JavaScript code that is not exactly trivial, I often reach for VS Code's debugger.
Today I realized that the configuration to help with this had not yet been committed, so here it is.
> Make it easier to work with this repository using VS Code

- update-scripts/tag-git.sh
This is a companion of https://github.com/git-for-windows/build-extra/pull/607
/cc @orgads
> tag-git: accommodate for upstream's `.txt` -> `.adoc` rename

- .github/actions/init-g4w-sdk-for-pacman/action.yml
actions/cache/restore [does a prefix match on the cache key to restore](https://github.com/actions/cache/issues/1433#issuecomment-2259294936). This can lead to restoring a different cache than we expect. In that case the cache-hit output is set to false, which further disturbs our workflows, since a cache was restored, but the output claims a cache miss.
To work around this, turn the makepkg suffix into an infix.
> init-g4w-sdk-for-pacman: work around caching issue
